version: "3.8"

services:
  # redis:
  #   image: redis
  #   container_name: redis
  #   expose:
  #     - 6379

  postgres:
    networks:
      - default
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/

  node:
    image: node
    networks:
      - proxy
      - default
    links:
      # - redis
      - postgres
    depends_on:
      # - redis
      - postgres
    env_file:
      - .env
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://cache
    volumes:
      - ./src/:/home/node/app:rw
    ports:
      - 8082:3000
    command: "npm start"

networks:
  proxy:
    external: true